language: go

services:
  - docker

go:
  - 1.13.x

jobs:
  include:
    - stage: "build"
      name: "build docker"
      script:
        - go get -u github.com/mailru/easyjson/...
        - ./scripts/run.sh

    - stage: "tests"
      name: "unit tests"
      script: cd internal/pkg/security && go test
