language: go
go:
  - 1.13.x
sudo: false
install:
  - go get -u github.com/mailru/easyjson/...
  - GO111MODULE=on
  - go mod vendor
  - easyjson --all ./app/domain/model
before_deploy:
  - openssl aes-256-cbc -K $encrypted_4a269b4e0d14_key -iv $encrypted_4a269b4e0d14_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - eval $(ssh-agent)
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p22 artbakulev@cinsear.ru "./backend/scripts/deployGo.sh -b $TRAVIS_BRANCH"
  on:
    repo: go-park-mail-ru/2019_2_Pirogi
    all_branches: true
