version: '3'
services:
  server:
    build:
      context: ./
      dockerfile: ./cmd/server/Dockerfile
    ports:
      #   поменял порт с 8000 на 8080 из-за бага в новой версии Docker для Mac
      - "8080:8080"
    depends_on:
      - mongo
    restart: always
    volumes:
      - "media:/media"
      - "log:/log"
    container_name: cinsear

  sessions:
    build:
      context: ./
      dockerfile: ./cmd/sessions/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    restart: always
    volumes:
      - "log:/log"
    container_name: cinsear-sessions

  users:
    build:
      context: ./
      dockerfile: ./cmd/users/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mongo
    restart: always
    volumes:
      - "log:/log"
    container_name: cinsear-users

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
      - ./mongoInit.js:/docker-entrypoint-initdb.d/mongoInit.js:ro
    container_name: cinsear-db
    environment:
      - MONGO_INITDB_DATABASE=cinsear
      - MONGO_INITDB_USERNAME=cinsear-user
      - MONGO_INITDB_PASSWORD=cinsear-pwd
volumes:
  media:
  log:
  db:
