global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'server'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['server:8080']

  - job_name: 'system'
    static_configs:
      - targets: ['nodeexporter:9100']
