// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sessions.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0475a55364240b58, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	CookieValue          string   `protobuf:"bytes,2,opt,name=cookieValue,proto3" json:"cookieValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0475a55364240b58, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *LoginResponse) GetCookieValue() string {
	if m != nil {
		return m.CookieValue
	}
	return ""
}

type LogoutRequest struct {
	CookieValue          string   `protobuf:"bytes,1,opt,name=cookieValue,proto3" json:"cookieValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0475a55364240b58, []int{2}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetCookieValue() string {
	if m != nil {
		return m.CookieValue
	}
	return ""
}

type LogoutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0475a55364240b58, []int{3}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

type LoginCheckRequest struct {
	CookieValue          string   `protobuf:"bytes,1,opt,name=cookieValue,proto3" json:"cookieValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginCheckRequest) Reset()         { *m = LoginCheckRequest{} }
func (m *LoginCheckRequest) String() string { return proto.CompactTextString(m) }
func (*LoginCheckRequest) ProtoMessage()    {}
func (*LoginCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0475a55364240b58, []int{4}
}

func (m *LoginCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginCheckRequest.Unmarshal(m, b)
}
func (m *LoginCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginCheckRequest.Marshal(b, m, deterministic)
}
func (m *LoginCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginCheckRequest.Merge(m, src)
}
func (m *LoginCheckRequest) XXX_Size() int {
	return xxx_messageInfo_LoginCheckRequest.Size(m)
}
func (m *LoginCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginCheckRequest proto.InternalMessageInfo

func (m *LoginCheckRequest) GetCookieValue() string {
	if m != nil {
		return m.CookieValue
	}
	return ""
}

type LoginCheckResponse struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginCheckResponse) Reset()         { *m = LoginCheckResponse{} }
func (m *LoginCheckResponse) String() string { return proto.CompactTextString(m) }
func (*LoginCheckResponse) ProtoMessage()    {}
func (*LoginCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0475a55364240b58, []int{5}
}

func (m *LoginCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginCheckResponse.Unmarshal(m, b)
}
func (m *LoginCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginCheckResponse.Marshal(b, m, deterministic)
}
func (m *LoginCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginCheckResponse.Merge(m, src)
}
func (m *LoginCheckResponse) XXX_Size() int {
	return xxx_messageInfo_LoginCheckResponse.Size(m)
}
func (m *LoginCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginCheckResponse proto.InternalMessageInfo

func (m *LoginCheckResponse) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "v1.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "v1.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "v1.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "v1.LogoutResponse")
	proto.RegisterType((*LoginCheckRequest)(nil), "v1.LoginCheckRequest")
	proto.RegisterType((*LoginCheckResponse)(nil), "v1.LoginCheckResponse")
}

func init() { proto.RegisterFile("sessions.proto", fileDescriptor_0475a55364240b58) }

var fileDescriptor_0475a55364240b58 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x4d, 0xa5, 0x41, 0xa7, 0x5a, 0xda, 0x41, 0x4b, 0xc9, 0xa9, 0xe4, 0xe4, 0x41, 0x02,
	0x51, 0x3c, 0x0a, 0x8a, 0x5e, 0x0a, 0x9e, 0x22, 0x78, 0x8f, 0x71, 0xb0, 0x4b, 0x6b, 0x26, 0x66,
	0xb2, 0xf1, 0x67, 0xf9, 0x17, 0x85, 0xcd, 0x6e, 0xba, 0x44, 0x10, 0x8f, 0xef, 0x25, 0xdf, 0x9b,
	0x37, 0xb3, 0x30, 0x15, 0x12, 0x51, 0x5c, 0x4a, 0x52, 0xd5, 0xdc, 0x30, 0x8e, 0xda, 0x34, 0xbe,
	0x83, 0x93, 0x27, 0x7e, 0x57, 0x65, 0x46, 0x9f, 0x9a, 0xa4, 0xc1, 0x33, 0x18, 0xd3, 0x47, 0xae,
	0x76, 0xcb, 0x60, 0x15, 0x5c, 0x1c, 0x67, 0x9d, 0xc0, 0x08, 0x8e, 0xaa, 0x5c, 0xe4, 0x8b, 0xeb,
	0xb7, 0xe5, 0xc8, 0x7c, 0xe8, 0x75, 0xbc, 0x86, 0x53, 0x9b, 0x20, 0x15, 0x97, 0x42, 0xb8, 0x80,
	0x50, 0x0b, 0xd5, 0xeb, 0x47, 0x93, 0x71, 0x98, 0x59, 0x85, 0x2b, 0x98, 0x14, 0xcc, 0x5b, 0x45,
	0x2f, 0xf9, 0x4e, 0x93, 0xcd, 0xf1, 0xad, 0x38, 0x35, 0x51, 0xac, 0x1b, 0xd7, 0x66, 0x80, 0x04,
	0xbf, 0x91, 0x19, 0x4c, 0x1d, 0xd2, 0x8d, 0x8f, 0x6f, 0x60, 0x6e, 0xfa, 0x3c, 0x6c, 0xa8, 0xd8,
	0xfe, 0x3f, 0xe8, 0x12, 0xd0, 0xc7, 0xfe, 0xde, 0xe5, 0xea, 0x3b, 0x80, 0xc9, 0xbd, 0x6e, 0x36,
	0xcf, 0x54, 0xb7, 0xaa, 0x20, 0x4c, 0x60, 0x6c, 0x68, 0x9c, 0x25, 0x6d, 0x9a, 0xf8, 0x17, 0x8d,
	0xe6, 0x9e, 0x63, 0x2b, 0x1e, 0xe0, 0x2d, 0xc0, 0x7e, 0x1a, 0x9e, 0xf7, 0xbf, 0xf8, 0xa5, 0xa3,
	0xc5, 0xd0, 0xee, 0xf1, 0x14, 0xc2, 0x6e, 0x6b, 0x74, 0xe9, 0xfb, 0xa3, 0x45, 0xe8, 0x5b, 0x0e,
	0x79, 0x0d, 0xcd, 0x9b, 0x5f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x3f, 0x62, 0x5a, 0x05,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	LoginCheck(ctx context.Context, in *LoginCheckRequest, opts ...grpc.CallOption) (*LoginCheckResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/v1.AuthService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) LoginCheck(ctx context.Context, in *LoginCheckRequest, opts ...grpc.CallOption) (*LoginCheckResponse, error) {
	out := new(LoginCheckResponse)
	err := c.cc.Invoke(ctx, "/v1.AuthService/LoginCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/v1.AuthService/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	LoginCheck(context.Context, *LoginCheckRequest) (*LoginCheckResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAuthServiceServer) LoginCheck(ctx context.Context, req *LoginCheckRequest) (*LoginCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginCheck not implemented")
}
func (*UnimplementedAuthServiceServer) Logout(ctx context.Context, req *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AuthService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_LoginCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).LoginCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AuthService/LoginCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).LoginCheck(ctx, req.(*LoginCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AuthService/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "LoginCheck",
			Handler:    _AuthService_LoginCheck_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _AuthService_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sessions.proto",
}
