cookie_auth_name: "cinsear_session"
cookie_auth_duration_hours: 10

access_log: "/log/access.log"
error_log: "/log/error.log"

users_image_upload_path: "/media/images/users/"
films_image_upload_path: "/home/artbakulev/media/images/films/"
persons_image_upload_path: "/media/images/persons/"

# Put the credentials of MongoDB user here
mongo_user: "cinsear-user"
mongo_pwd: "cinsear-pwd"
mongo_host: "mongodb://mongo:27017"
mongo_db_name: "cinsear"

counters_collection_name: "counters"
users_collection_name: "users"
cookies_collection_name: "cookies"
films_collection_name: "films"
persons_collection_name: "persons"
likes_collection_name: "likes"
reviews_collection_name: "reviews"
lists_collection_name: "lists"
subscriptions_collection_name: "subscription"

user_target_name: "user"
film_target_name: "film"
cookie_target_name: "cookie"
person_target_name: "domains"
review_target_name: "review"
like_target_name: "like"
star_target_name: "star"
list_target_name: "list"
subscription_target_name: "subscription"
film_image_target_name: "filmimage"
person_image_target_name: "personimage"
default_image_name: "default.png"

#   поменял порт с 8000 на 8080 из-за бага в новой версии Docker для Mac
api_port: ":8080"

csrf_header: "X-CSRF-TOKEN"
csrf_cookie_name: "_csrf"

default_entries_limit: 10

default_order_by: "mark"
default_year_min: 1700
default_year_max: 2020

max_file_upload_size: 5242880 # 5 MB

sessions_microservice_port: ":8081"
users_microservice_port: ":8082"