cookie_auth_name: "cinsear_session"
cookie_auth_duration_hours: 10

access_log: "/log/access.log"
error_log: "/log/error.log"

users_image_upload_path: "/media/images/users/"
films_image_upload_path: "/media/images/films/"
persons_image_upload_path: "/media/images/films/"

# Put the credentials of MongoDB user here
mongo_user: "cinsear-user"
mongo_pwd: "cinsear-pwd"
mongo_host: "mongodb://mongo:27017"
mongo_db_name: "cinsear"

users_collection_name: "users"
cookies_collection_name: "cookies"
films_collection_name: "films"
persons_collection_name: "persons"
likes_collection_name: "likes"
reviews_collection_name: "reviews"
counters_collection_name: "counters"

user_target_name: "user"
film_target_name: "film"
cookie_target_name: "cookie"
person_target_name: "person"
review_target_name: "review"
like_target_name: "like"
star_target_name: "star"

api_port: ":8000"

csrf_header: "X-CSRF-TOKEN"
csrf_cookie_name: "_csrf"

default_entries_limit: 10