headers:
  Access-Control-Allow-Origin: "*"
  Cache-Control: "no-store, no-cache, must-revalidate, post-check=0, pre-check=0"
  Content-Type: "application/json; charset=UTF-8"
  Vary: "Accept-Encoding"
  Access-Control-Allow-Credentials: "true"
